spring.application.name=norris

server.port=8080

#spring.datasource.url=jdbc:postgresql://localhost:5432/mailing
spring.datasource.url=postgresql://postgres:MexLcfBIKntQHXtxwAhRjSpLESywqIAO@yamabiko.proxy.rlwy.net:33178/railway
spring.datasource.username=postgres
spring.datasource.password=MexLcfBIKntQHXtxwAhRjSpLESywqIAO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
bling.token=
bling.client-id=8369e83d6a777149f047a7c3eba423700145d0f7
bling.client-secret=96b582e37f56a422cc2e1f92c8b4b0e22f1a97170ed84120b6180995276c
bling.redirect-uri=http://localhost:8080/bling/callback